FROM node:22-alpine AS build
WORKDIR /app
COPY PaymentApp/package*.json .
RUN npm install
COPY PaymentApp/. .
RUN npm run build

FROM nginx:alpine AS final
COPY --from=build /app/dist/payment-app /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY Docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
